export const catsData = [
  {
    emotionTags: ["Moody"],
    isGif: false,
    image: "angry.jpeg",
    alt: "A cat looking moody",
  },
  {
    emotionTags: ["Moody", "Insomniac"],
    isGif: false,
    image: "angry2.jpeg",
    alt: "A cat looking moody",
  },
  {
    emotionTags: ["Moody"],
    isGif: false,
    image: "angry3.jpeg",
    alt: "A cat looking moody",
  },
  {
    emotionTags: ["Confused", "Sad"],
    isGif: false,
    image: "confused.jpeg",
    alt: "A cat looking confused",
  },
  {
    emotionTags: ["Dominant", "Moody"],
    isGif: false,
    image: "dominant.jpeg",
    alt: "A cat looking dominant",
  },
  {
    emotionTags: ["Happy", "Relaxed"],
    isGif: false,
    image: "happy.jpeg",
    alt: "A cat looking happy",
  },
  {
    emotionTags: ["Hungry"],
    isGif: false,
    image: "hungry.jpeg",
    alt: "A cat looking hungry",
  },
  {
    emotionTags: ["Hungry"],
    isGif: false,
    image: "hungry1.jpeg",
    alt: "A cat looking hungry",
  },
  {
    emotionTags: ["Insomniac"],
    isGif: false,
    image: "insomnia.jpeg",
    alt: "A cat looking insomniac",
  },
  {
    emotionTags: ["Insomniac"],
    isGif: false,
    image: "insomnia1.jpeg",
    alt: "A cat looking insomniac",
  },
  {
    emotionTags: ["Relaxed"],
    isGif: false,
    image: "lazy.jpeg",
    alt: "A cat looking lazy",
  },
  {
    emotionTags: ["Scared"],
    isGif: false,
    image: "nervous.jpeg",
    alt: "A cat looking nervous",
  },
  {
    emotionTags: ["Sad"],
    isGif: false,
    image: "sad.jpeg",
    alt: "A cat looking sad",
  },
  {
    emotionTags: ["Sad", "Moody"],
    isGif: false,
    image: "sad1.jpeg",
    alt: "A cat looking sad",
  },
  //   Gifs start here ---------------------------------------
  {
    emotionTags: ["Moody"],
    isGif: true,
    image: "angry.gif",
    alt: "A cat looking moody",
  },
  {
    emotionTags: ["Moody"],
    isGif: true,
    image: "angry2.gif",
    alt: "A cat looking angry",
  },
  {
    emotionTags: ["Confused"],
    isGif: true,
    image: "confused2.gif",
    alt: "A cat looking confused",
  },
  {
    emotionTags: ["Dominant"],
    isGif: true,
    image: "dominant.gif",
    alt: "A cat looking dominant",
  },
  {
    emotionTags: ["Happy"],
    isGif: true,
    image: "happy.gif",
    alt: "A cat looking happy",
  },
  {
    emotionTags: ["Hungry", "Sad", "Confused"],
    isGif: true,
    image: "confused.gif",
    alt: "A cat looking hungry",
  },
  {
    emotionTags: ["Hungry"],
    isGif: true,
    image: "hungry.gif",
    alt: "A cat looking hungry",
  },
  {
    emotionTags: ["Hungry"],
    isGif: true,
    image: "hungry2.gif",
    alt: "A cat looking hungry",
  },
  {
    emotionTags: ["Insomniac", "Scared"],
    isGif: true,
    image: "insomnia2.gif",
    alt: "A cat looking insomniac",
  },
  {
    emotionTags: ["Relaxed"],
    isGif: true,
    image: "lazy.gif",
    alt: "A cat looking relaxed",
  },
  {
    emotionTags: ["Relaxed"],
    isGif: true,
    image: "relaxed2.gif",
    alt: "A cat looking relaxed",
  },
  {
    emotionTags: ["Scared", "Sad"],
    isGif: true,
    image: "nervous.gif",
    alt: "A cat looking nervous",
  },
  {
    emotionTags: ["Scared"],
    isGif: true,
    image: "nervous2.gif",
    alt: "A cat looking scared",
  },
  {
    emotionTags: ["Sad"],
    isGif: true,
    image: "sad.gif",
    alt: "A cat looking sad",
  },
];
